name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          rustc --version

          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli --version 0.2.100
          wasm-bindgen --version

          cd web
          chmod +x ./build_wasm.sh
          ./build_wasm.sh

          cp -r ../assets .

          ls -al .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
