[package]
name = "web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy_flappy_bird = { path = "..", features = [
    "inspector",
], default-features = false }
bevy = "0.14.1"
wasm-bindgen = "0.2.93"
# wasm-bindgen-futures = "0.4.43"
